import { useTaskMutations } from "./useTasks";
import { useGoalMutations } from "./useGoals";
import { useItineraryMutations } from "./useItineraries";
import { useCharacterMutations } from "./useCharacters";
import { useJournalMutations } from "./useJournals";
import { useEventMutations } from "./useEvents";
import { BrainDump } from "@/types/brain-dump";
import { DEFAULT_CHAPTER_ID } from "../constants";
import { toast } from "@/components/ui/sonner";
import { useState } from "react";

export const useBrainDump = () => {
  const { addMutation: addTask } = useTaskMutations();
  const { addMutation: addGoal } = useGoalMutations();
  const { addMutation: addItinerary } = useItineraryMutations();
  const { addMutation: addCharacter } = useCharacterMutations();
  const { addMutation: addJournal } = useJournalMutations(DEFAULT_CHAPTER_ID);
  const { addMutation: addEvent } = useEventMutations();

  const [isProcessing, setIsProcessing] = useState(false);

  const processBrainDump = async (data: BrainDump, selectedIndices: Record<string, number[]>) => {
    setIsProcessing(true);
    const results = {
      success: 0,
      total: 0,
    };

    try {
      // Process Tasks
      if (data.tasks && selectedIndices.tasks) {
        for (const index of selectedIndices.tasks) {
          const task = data.tasks[index];
          results.total++;
          try {
            await addTask.mutateAsync(task as any);
            results.success++;
          } catch (e) {
            console.error("Failed to add task", task, e);
          }
        }
      }

      // Process Goals
      if (data.goals && selectedIndices.goals) {
        for (const index of selectedIndices.goals) {
          const goal = data.goals[index];
          results.total++;
          try {
            await addGoal.mutateAsync(goal as any);
            results.success++;
          } catch (e) {
            console.error("Failed to add goal", goal, e);
          }
        }
      }

      // Process Itineraries
      if (data.itineraries && selectedIndices.itineraries) {
        for (const index of selectedIndices.itineraries) {
          const itinerary = data.itineraries[index];
          results.total++;
          try {
            await addItinerary.mutateAsync(itinerary as any);
            results.success++;
          } catch (e) {
            console.error("Failed to add itinerary", itinerary, e);
          }
        }
      }

      // Process Characters
      if (data.characters && selectedIndices.characters) {
        for (const index of selectedIndices.characters) {
          const character = data.characters[index];
          results.total++;
          try {
            await addCharacter.mutateAsync(character as any);
            results.success++;
          } catch (e) {
            console.error("Failed to add character", character, e);
          }
        }
      }

      // Process Journals
      if (data.journals && selectedIndices.journals) {
        for (const index of selectedIndices.journals) {
          const journal = data.journals[index];
          results.total++;
          try {
            // Journals need a chapterId. Using default.
            await addJournal.mutateAsync({
              ...journal,
              chapterId: DEFAULT_CHAPTER_ID,
              iv: "", // Will be generated by mutation
            } as any);
            results.success++;
          } catch (e) {
            console.error("Failed to add journal", journal, e);
          }
        }
      }

      // Process Events
      if (data.events && selectedIndices.events) {
        for (const index of selectedIndices.events) {
          const event = data.events[index];
          results.total++;
          try {
            await addEvent.mutateAsync(event as any);
            results.success++;
          } catch (e) {
            console.error("Failed to add event", event, e);
          }
        }
      }

      if (results.success > 0) {
        toast.success(`Success! Added ${results.success} items.`);
      } else if (results.total > 0) {
        toast.error("Failed to add any items. Please try again.");
      }

      return results;
    } finally {
      setIsProcessing(false);
    }
  };

  return { processBrainDump, isProcessing };
};
